### ISSUE TITLE
Infinite Loop and debugOnly?

### ISSUE THREAD

**Issue by pcorey** [JackAdams/meteor-editable-json#7]
Hi,

If I'm understanding this code right, it looks like the `editableJSON_update` slips into an [infinite loop](https://github.com/JackAdams/meteor-editable-json/blob/master/editable-json-common.js#L5-L7) when it calls `EditableJSON.collection(collectionName);`? I might be misunderstanding what's going on.

Also, I recently accepted a [pull request](https://github.com/East5th/package-scan/pull/1) for my `east5th:package-scan` security project for older versions of this package. If this isn't intended as a production package, it may be helpful to add the [debugOnly](http://docs.meteor.com/#/full/packagedescription) flag to prevent it from building into release bundles.

No rush, I was just curious.

**Comment by JackAdams** [comment]
Haha... yeah, you're totally right. I saw that it was on the `package-scan` list a week or two back and was surprised to discover I hadn't ever added a `debugOnly` flag.  I will in the next release (which will be soonish -- like within the next few days).

It certainly looks like there's an infinite loop happening when `EditableJSON.collection` gets called.  I'll look into this.  Looks like some artefact from a refactor that never gets called anymore.

Thanks for alerting me to these things.

**Comment by JackAdams** [comment]
Just released 0.6.1, which addresses both of these issues.

**Comment by pcorey** [comment]
Nice, that was fast!
